# Generated by Django 5.2.10 on 2026-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_articulo_imagen'),
        ('destinos', '0002_destino_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='destinos',
            field=models.ManyToManyField(blank=True, help_text='Destinos a los que aplica esta guía (puede ser más de uno).', related_name='articulos', to='destinos.destino'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='relacionados_manual',
            field=models.ManyToManyField(blank=True, help_text='Artículos recomendados manualmente (prioridad sobre los automáticos).', related_name='relacionado_por', to='contenido.articulo'),
        ),
    ]
