# Generated by Django 5.2.10 on 2026-02-03 15:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_guiasindexpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion_corta', models.CharField(blank=True, max_length=180)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Guías',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría editorial (opcional, recomendado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='pages.categoriapage'),
        ),
    ]
