# Generated by Django 5.2.10 on 2026-02-03 17:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_categoriapage_articulopage_categoria'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Índice de Destinos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PaisPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion_corta', models.CharField(blank=True, max_length=180)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'País',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeccionDestinoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {'icon': 'image'})})),
            ],
            options={
                'verbose_name': 'Sección de destino',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DestinoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion_corta', models.CharField(blank=True, max_length=180)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero del destino (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Destino',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='destino_principal',
            field=models.ForeignKey(blank=True, help_text='Destino principal sobre el que trata la guía (recomendado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='pages.destinopage'),
        ),
    ]
