# Generated by Django 5.2.10 on 2026-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_destinosindexpage_paispage_secciondestinopage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link de YouTube/Vimeo que complemente el artículo (recorrido, experiencia o vista real). Opcional.'),
        ),
    ]
