# Generated by Django 5.2.10 on 2026-02-04 14:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_articulopage_video_url'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='categoriapage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='destinosindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guiasindexpage',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='paispage',
            options={'verbose_name': 'Índice de Destinos'},
        ),
        migrations.RemoveField(
            model_name='destinosindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='articulopage',
            name='destacado',
            field=models.BooleanField(default=False, help_text='...'),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='destinos',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Destinos a los que aplica esta guía (puede ser más de uno).', related_name='guias_m2m', to='pages.destinopage'),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='relacionados_manual',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Guías recomendadas manualmente (prioridad sobre automáticas).', related_name='relacionado_por_manual', to='pages.articulopage'),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en la home como destacado'),
        ),
    ]
