# Generated by Django 5.2.10 on 2026-02-04 16:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepage_alter_categoriapage_options_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Página simple',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='categoriapage',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='destinosindexpage',
            options={'verbose_name': 'Índice de Destinos'},
        ),
        migrations.AlterModelOptions(
            name='guiasindexpage',
            options={'verbose_name': 'Índice de Guías'},
        ),
        migrations.AlterModelOptions(
            name='paispage',
            options={'verbose_name': 'País'},
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar como destacado en la home (si corresponde).'),
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link de YouTube/Vimeo que complemente el artículo (opcional).'),
        ),
    ]
