# Generated by Django 5.2.10 on 2026-02-04 17:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_simplepage_alter_categoriapage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulopage',
            options={'verbose_name': 'Artículo'},
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='destino_principal',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='destinos',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='relacionados_manual',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='destacado',
        ),
        migrations.AddField(
            model_name='articulopage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 2), ('rich_text', 3), ('image', 6), ('gallery', 10), ('highlights', 15), ('info_grid', 19), ('map', 21), ('youtube', 23), ('cta', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('images', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('items', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('label', 16), ('value', 0)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('title', 7), ('rows', 18)]], {}), 20: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá la URL del mapa o iframe URL de Google Maps', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('title', 7), ('map', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('title', 7), ('video', 22)]], {}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('text', 16), ('url', 24), ('note', 25)]], {})}),
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 2), ('rich_text', 3), ('image', 6), ('gallery', 10), ('highlights', 15), ('youtube', 17), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('images', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('items', 14)]], {}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('title', 7), ('video', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 19: ('wagtail.blocks.URLBlock', (), {'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 18), ('url', 19), ('note', 20)]], {})}),
        ),
        migrations.AlterField(
            model_name='destinopage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='destinopage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('youtube', 3), ('image', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol']}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('video', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {})}),
        ),
        migrations.DeleteModel(
            name='SeccionDestinoPage',
        ),
    ]
