# Generated by Django 5.2.10 on 2026-02-06 15:46

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_articulopage_seo_description_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinopage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 2), ('rich_text', 3), ('image', 6), ('gallery', 10), ('highlights', 15), ('info_grid', 19), ('map', 21), ('youtube', 23), ('cta', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('images', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('items', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('label', 16), ('value', 0)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'min_num': 1}), 19: ('wagtail.blocks.StructBlock', [[('title', 7), ('rows', 18)]], {}), 20: ('wagtail.blocks.URLBlock', (), {'help_text': 'Pegá la URL /maps/embed?... (NO el iframe completo)', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('title', 7), ('map_url', 20)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('title', 7), ('video', 22)]], {}), 24: ('wagtail.blocks.URLBlock', (), {'required': True}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('text', 16), ('url', 24), ('note', 25)]], {})}),
        ),
        migrations.CreateModel(
            name='DestinoPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='pages.destinopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='destinopage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pages.DestinoPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
