# Generated by Django 5.2.10 on 2026-02-06 16:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_paispage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinopage',
            name='cta_manual',
            field=wagtail.fields.StreamField([('cta', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1), ('note', 2)]], {})}),
        ),
    ]
