# Generated by Django 5.2.10 on 2026-02-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_destinopage_cta_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinopage',
            name='faq_1_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_1_q',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_2_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_2_q',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_3_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_3_q',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
