# Generated by Django 5.2.10 on 2026-02-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_destinopage_faq_1_a_destinopage_faq_1_q_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_1_a',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_1_q',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_2_a',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_2_q',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_3_a',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_3_q',
        ),
    ]
