# Generated by Django 5.2.10 on 2026-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_destinopage_faq_1_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinopage',
            name='faq_1_a',
            field=models.TextField(blank=True, verbose_name='FAQ 1 - Respuesta'),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_1_q',
            field=models.CharField(blank=True, max_length=180, verbose_name='FAQ 1 - Pregunta'),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_2_a',
            field=models.TextField(blank=True, verbose_name='FAQ 2 - Respuesta'),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_2_q',
            field=models.CharField(blank=True, max_length=180, verbose_name='FAQ 2 - Pregunta'),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_3_a',
            field=models.TextField(blank=True, verbose_name='FAQ 3 - Respuesta'),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='faq_3_q',
            field=models.CharField(blank=True, max_length=180, verbose_name='FAQ 3 - Pregunta'),
        ),
    ]
