# Generated by Django 5.2.10 on 2026-02-11 13:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_destinopage_faq_1_a_destinopage_faq_1_q_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinopage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Pregunta', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
    ]
