# Generated by Django 5.2.10 on 2026-02-11 15:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_destinopage_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_1_a',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_1_q',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_2_a',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_2_q',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_3_a',
        ),
        migrations.RemoveField(
            model_name='destinopage',
            name='faq_3_q',
        ),
        migrations.AlterField(
            model_name='destinopage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Preguntas frecuentes', 'label': 'Título (opcional)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Pregunta', 'max_length': 180, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Respuesta', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Preguntas', 'min_num': 1}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 4)]], {})}),
        ),
    ]
