# Generated by Django 5.2.10 on 2026-02-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_destinopage_faq_1_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
    ]
