# Generated by Django 5.2.10 on 2026-02-13 15:53

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_homepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopage',
            name='destinos',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='guias', to='pages.destinopage'),
        ),
    ]
