# Generated by Django 5.2.11 on 2026-02-13 18:15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_articulopage_destinos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulopage',
            name='destinos',
        ),
        migrations.CreateModel(
            name='ArticuloDestinoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('articulo', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos_relacionados', to='pages.articulopage')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_relacionados', to='pages.destinopage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
