# Generated by Django 5.2.11 on 2026-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_articulopage_destinos_articulodestinorelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulodestinorelation',
            options={},
        ),
        migrations.AddConstraint(
            model_name='articulodestinorelation',
            constraint=models.UniqueConstraint(fields=('articulo', 'destino'), name='unique_articulo_destino_relation'),
        ),
    ]
