# Generated by Django 5.2.11 on 2026-02-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_cleanup_duplicates_before_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulodestinorelation',
            name='unique_articulo_destino_relation_v2',
        ),
    ]
