# Generated by Django 5.2.11 on 2026-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_articulodestinorelation_unique_articulo_destino_relation_v2'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articulodestinorelation',
            constraint=models.UniqueConstraint(fields=('articulo', 'destino'), name='unique_articulo_destino_relation'),
        ),
    ]
