# Generated by Django 5.2.11 on 2026-02-18 16:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_articulodestinorelation_unique_articulo_destino_relation'),
    ]

    operations = []
