# Generated by Django 5.2.11 on 2026-02-18 16:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_articulodestinorelation_unique_articulo_destino_relation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulodestinorelation',
            name='unique_articulo_destino_relation_v3',
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 2), ('rich_text', 3), ('image', 6), ('gallery', 10), ('highlights', 15), ('youtube', 17), ('cta', 21), ('quick_sections', 33), ('quick_section', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('images', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('items', 14)]], {}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('title', 7), ('video', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 19: ('wagtail.blocks.URLBlock', (), {'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 18), ('url', 19), ('note', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Título del bloque (opcional)', 'max_length': 80, 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 80, 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo (opcional)', 'max_length': 140, 'required': False}), 25: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'help_text': 'Escribí el contenido de la sección. Evitá usar H2/H3 aquí: el título ya se renderiza arriba.', 'label': 'Contenido', 'required': False}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen (opcional)', 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de imagen (opcional)', 'max_length': 180, 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón (opcional)', 'max_length': 40, 'required': False}), 29: ('wagtail.blocks.URLBlock', (), {'label': 'URL del botón (opcional)', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Nota (opcional)', 'max_length': 120, 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('title', 23), ('subtitle', 24), ('body', 25), ('image', 26), ('caption', 27), ('cta_text', 28), ('cta_url', 29), ('cta_note', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {'label': 'Secciones', 'min_num': 1}), 33: ('wagtail.blocks.StructBlock', [[('title', 22), ('sections', 32)]], {})}),
        ),
        migrations.AddConstraint(
            model_name='articulodestinorelation',
            constraint=models.UniqueConstraint(fields=('articulo', 'destino'), name='unique_articulo_destino_relation'),
        ),
    ]
