# Generated by Django 5.2.11 on 2026-02-18 18:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_add_unique_constraint_v4'),
    ]

    operations = [
  
    ]
