# Generated by Django 5.2.11 on 2026-02-23 13:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_articulopage_body_alter_destinopage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulopage',
            options={},
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='articulopage',
            name='seo_description',
        ),
        migrations.AddField(
            model_name='articulopage',
            name='contenido_bruto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destinopage',
            name='contenido_bruto',
            field=models.TextField(blank=True, help_text='Pegá HTML (Docs/Word). Al guardar, se convierte a bloques automáticamente.'),
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 2), ('rich_text', 3), ('image', 6), ('gallery', 10), ('highlights', 15), ('youtube', 17), ('cta', 21), ('quick_sections', 33), ('quick_section', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('images', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('items', 14)]], {}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 7), ('video', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 19: ('wagtail.blocks.URLBlock', (), {'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 18), ('url', 19), ('note', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Título del bloque (opcional)', 'max_length': 80, 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 80, 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo (opcional)', 'max_length': 140, 'required': False}), 25: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'help_text': 'Escribí el contenido de la sección. Evitá usar H2/H3 aquí: el título ya se renderiza arriba.', 'label': 'Contenido', 'required': False}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen (opcional)', 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de imagen (opcional)', 'max_length': 180, 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón (opcional)', 'max_length': 40, 'required': False}), 29: ('wagtail.blocks.URLBlock', (), {'label': 'URL del botón (opcional)', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Nota (opcional)', 'max_length': 120, 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('title', 23), ('subtitle', 24), ('body', 25), ('image', 26), ('caption', 27), ('cta_text', 28), ('cta_url', 29), ('cta_note', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {'label': 'Secciones', 'min_num': 1}), 33: ('wagtail.blocks.StructBlock', [[('title', 22), ('sections', 32)]], {})}),
        ),
        migrations.AlterField(
            model_name='destinopage',
            name='body',
            field=wagtail.fields.StreamField([('quick_sections', 11), ('quick_section', 9), ('section_title', 14), ('rich_text', 15), ('image', 18), ('gallery', 22), ('highlights', 27), ('info_grid', 31), ('map', 33), ('youtube', 35), ('cta', 38)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título del bloque (opcional)', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 80, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo (opcional)', 'max_length': 140, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'help_text': 'Escribí el contenido de la sección. Evitá usar H2/H3 aquí: el título ya se renderiza arriba.', 'label': 'Contenido', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen (opcional)', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de imagen (opcional)', 'max_length': 180, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón (opcional)', 'max_length': 40, 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL del botón (opcional)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Nota (opcional)', 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 2), ('body', 3), ('image', 4), ('caption', 5), ('cta_text', 6), ('cta_url', 7), ('cta_note', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Secciones', 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('sections', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('image', 16), ('caption', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 21: ('wagtail.blocks.ListBlock', (20,), {'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('title', 19), ('images', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 23), ('text', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'min_num': 1}), 27: ('wagtail.blocks.StructBlock', [[('title', 19), ('items', 26)]], {}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 29: ('wagtail.blocks.StructBlock', [[('label', 28), ('value', 12)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'min_num': 1}), 31: ('wagtail.blocks.StructBlock', [[('title', 19), ('rows', 30)]], {}), 32: ('wagtail.blocks.URLBlock', (), {'help_text': 'Pegá la URL /maps/embed?... (NO el iframe completo)', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('title', 19), ('map_url', 32)]], {}), 34: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('title', 19), ('video', 34)]], {}), 36: ('wagtail.blocks.URLBlock', (), {'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('text', 28), ('url', 36), ('note', 37)]], {})}),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('youtube', 3), ('image', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ul', 'ol']}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('video', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {})}),
        ),
    ]
