# Generated by Django 5.2.11 on 2026-02-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_articulopage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinopage',
            name='contenido_bruto',
        ),
        migrations.AddField(
            model_name='destinopage',
            name='bulk_paste',
            field=models.TextField(blank=True, default='', help_text='Pegá HTML (Docs/Word). Al guardar, se convierte a bloques automáticamente.'),
        ),
    ]
