# Generated by Django 5.2.11 on 2026-02-23 14:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_destinopage_contenido_bruto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulopage',
            name='body',
            field=wagtail.fields.StreamField([('section_title', 2), ('rich_text', 3), ('image', 6), ('gallery', 10), ('highlights', 15), ('map', 17), ('youtube', 19), ('cta', 23), ('quick_sections', 35), ('quick_section', 33)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('images', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 7), ('items', 14)]], {}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Pegá la URL /maps/embed?... (NO el iframe completo)', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 7), ('map_url', 16)]], {}), 18: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Pegá el link de YouTube (o cualquier embed compatible)', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 7), ('video', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 21: ('wagtail.blocks.URLBlock', (), {'required': True}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('text', 20), ('url', 21), ('note', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Título del bloque (opcional)', 'max_length': 80, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 80, 'required': True}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo (opcional)', 'max_length': 140, 'required': False}), 27: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'help_text': 'Escribí el contenido de la sección. Evitá usar H2/H3 aquí: el título ya se renderiza arriba.', 'label': 'Contenido', 'required': False}), 28: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen (opcional)', 'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'label': 'Pie de imagen (opcional)', 'max_length': 180, 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Texto del botón (opcional)', 'max_length': 40, 'required': False}), 31: ('wagtail.blocks.URLBlock', (), {'label': 'URL del botón (opcional)', 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'label': 'Nota (opcional)', 'max_length': 120, 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('title', 25), ('subtitle', 26), ('body', 27), ('image', 28), ('caption', 29), ('cta_text', 30), ('cta_url', 31), ('cta_note', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {'label': 'Secciones', 'min_num': 1}), 35: ('wagtail.blocks.StructBlock', [[('title', 24), ('sections', 34)]], {})}),
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='contenido_bruto',
            field=models.TextField(blank=True, default='', help_text='Pegá HTML (Docs/Word). Al guardar, se convierte a bloques automáticamente.'),
        ),
    ]
