# Generated by Django 5.2.11 on 2026-02-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_articulopage_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulopage',
            old_name='contenido_bruto',
            new_name='bulk_paste',
        ),
    ]
