# Generated by Django 5.2.11 on 2026-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_ensure_bulk_paste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulopage',
            name='contenido_bruto',
        ),
        migrations.AddField(
            model_name='articulopage',
            name='bulk_paste',
            field=models.TextField(blank=True, default='', help_text='Pegá HTML (Docs/Word). Al guardar, se convierte a bloques automáticamente.'),
        ),
    ]
