# Generated by Django 5.2.11 on 2026-02-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_articulopage_body_alter_destinopage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='articulopage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
