# Generated by Django 5.2.10 on 2026-01-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('resumen', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='destinos.pais')),
            ],
            options={
                'ordering': ['pais__nombre', 'nombre'],
                'unique_together': {('pais', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SeccionDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('contenido', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='destinos.destino')),
            ],
            options={
                'ordering': ['orden', 'titulo'],
                'unique_together': {('destino', 'slug')},
            },
        ),
    ]
