# Generated by Django 5.2.10 on 2026-01-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/'),
        ),
    ]
