# Generated by Django 5.2.10 on 2026-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_destino_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AddField(
            model_name='pais',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paises/'),
        ),
    ]
